version: 2
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    working_directory: /tmp
    steps:
      - checkout
      - run: yarn && yarn release --x64 --ia32 --linux --win
      - run: mkdir /tmp/artifacts
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts

  build_macos:
    macos:
      xcode: "14.0.0"
    working_directory: /tmp
    steps:
      - checkout
      - run: yarn && yarn release
      - run: mkdir /tmp/artifacts
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build:
    jobs:
      - build_windows
      - build_macos